version: "2"

services:
  db:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=Root@1234
      - MYSQL_DATABASE=epaper
  ports:
      - "3306:3306"
  app:
    image: iappscodingtask:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/epaper
    depends_on:
      - db